import frameself.format.*;
import java.util.Date;
import java.util.ArrayList;

rule "CreateContainerFailedAction"
    when
       Rfc(category == "TRY_OTHER_OVH_CREATE_CONTAINER", $value : value)
    then 
	   ArrayList<Attribute> attributes = new ArrayList<Attribute>();
   	   attributes.add(new Attribute("value", $value));
   	   Action action = new Action();
	   action.setAttributes(attributes);
   	   action.setCategory("CREATE_CONTAINER_ACTION");
   	   action.setTimestamp(new Date());
	   action.setName("CREATE_CONTAINER");
	   action.setEffector(new Effector("BACKEND"));
       insert(action);
end

